[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift = "0.113.0"
cranelift-module = "0.113.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
